# Generated by Django 5.0.6 on 2024-07-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Characters",
            new_name="Character",
        ),
    ]
